#schema des Factures
Facture:
  definition:
    fields:
      _id: {}
      _rev: {}
      type: {}
      identifiant: {}
      code_comptable_client: {}
      numero_facture: {}
      numero_ava: {}
      numero_adherent: {}
      date_emission: {}
      date_facturation: {}
      date_paiement: {}
      date_echeance: {}
      reglement_paiement: {}
      montant_paiement: {}
      campagne: {}
      numero_archive: {  }
      statut: {}
      avoir: {required: false}
      taux_tva: {required: false}
      region: {}
      versement_comptable: {type: integer}
      versement_comptable_paiement: {type: integer}
      arguments: 
        type: collection
        definition:
          fields:
            '*': {  }
      message_communication: {required: false}
      emetteur:
        type: collection
        definition:
          fields:
            adresse: {}
            code_postal: {}
            ville: {}
            service_facturation: {}
            telephone: {}
            email: {required: false}
      declarant:
        type: collection
        definition:
          fields:
            nom: {  }
            num_tva_intracomm: {    }
            adresse: {  }
            commune: {  }
            code_postal: {   }
            raison_sociale: {  }
      total_ht: {type: float}
      total_ttc: {type: float}
      total_taxe: {type: float}
      lignes:
        type: collection
        class: FactureLignes
        definition:
          fields:
            '*':
              class: FactureLigne
              type: collection
              definition:
                fields:
                  libelle: {  }
                  produit_identifiant_analytique: {  }
                  montant_tva: {type: float}
                  montant_ht: {type: float}
                  origine_mouvements:
                    type: collection
                    definition:
                      fields:
                        '*':
                          type: array_collection
                          definition:
                            fields:
                              '*': { }
                  details:
                    type: array_collection
                    definition:
                      fields:
                        '*':
                          type: collection
                          definition:
                            fields:
                              libelle: {}
                              quantite: {type: float}
                              taux_tva: {type: float}
                              prix_unitaire: {type: float}
                              montant_tva: {type: float}
                              montant_ht: {type: float}
      echeances:
        type: array_collection
        definition:
          fields:
            '*':
              type: collection
              definition:
                fields:
                  echeance_code: {}
                  echeance_date: {}
                  montant_ttc: {type: float}
      origines:
        type: collection
        definition:
          fields:
            #DRM ou SRV ID => "libelle"
            '*': {}
      templates:
        type: collection
        definition:
          fields:
            #DRM ou SRV ID => "libelle"
            '*': {}
