all:
  configuration:
    facture:
      pdf_nom_interpro: "CIVA"
      pdf_ordre_cheque: "Conseil Interprofessionnel des Vins d'Alsace"
      prefix_sage: "VEN"
      tva_compte: "44570100"
      stockage_code_produit: "identifiant_analytique"
      pdf_produit: false
      pdf_nom_ref_client: "N° ADHÉRENT"
      pdf_nom_taux: "Taux"
      pdf_display_code_comptable: false
