all:
  configuration:
    societe:
      identifiant_etablissement_saisi: true
      identifiant_etablissement_saisi_help: "- le numéro CVI\n- ou un numéro interne de 10 chiffres précédé d'un \"C\"\n- ou les 9 chiffres du SIREN"
      droits:
        admin: "Admin"
        teledeclaration: "Télédéclaration"
        teledeclaration_dr: "DR"
        teledeclaration_dr_acheteur: "DR Acheteur"
        teledeclaration_gamma: "Gamma"
        teledeclaration_vrac: "Signature contrats"
        teledeclaration_vrac_creation: "Création contrats"
        teledeclaration_ds_propriete: "DS Propriété"
        teledeclaration_ds_negoce: "DS Négoce"
        teledeclaration_drm: "DRM"
        teledeclaration_douane: "Transmission Ciel"
        extranet_admin: "Extranet Admin"
        extranet_editeur: "Extranet Éditeur"
        extranet_salarie: "Extranet Salarié"
        extranet_conseil_direction: "Extranet Conseil de direction"
        extranet_technique: "Extranet Technique"
        extranet_organisation: "Extranet Organisation"
        extranet_partenaire: "Extranet Partenaire"
      extras:
        cvi: { nom: "cvi", auto: 'etablissement->cvi' }
        civaba: { nom: "civaba", auto: 'etablissement->num_interne' }
        siret: { nom: "siret", auto: 'societe->siret|etablissement->siret' }
        no_accises: { nom: "no_accises", auto: 'etablissement->no_accises' }
        carte_pro: { nom: "carte_pro", auto: 'etablissement->carte_pro' }
        code_comptable: { nom: "code_comptable", auto: 'societe->code_comptable_client' }
        famille: { nom: "famille", auto: 'etablissement->famille' }
        region: { nom: "region", auto: 'societe->getRegionViticole()|etablissement->region' }
        acheteur_raisin: { nom: "acheteur_raisin", auto: 'etablissement->acheteur_raisin'  }
        activite: { nom: "activité" }
        cooperative: { nom: "coopérative" }
        site_internet: { nom: "site_internet", auto: 'societe->site_internet|etablissement->site_internet' }
        sous_region_viticole: { nom: "sous_region_viticole" }
        adherent_organisme: { nom: "adherent_organisme" }
        declaration_commune: { nom: "declaration_commune", auto: 'etablissement->declaration_commune' }
        declaration_insee: { nom: "declaration_insee", auto: 'etablissement->declaration_insee' }
        societes_liees_identifiant: { nom: "societes_liees_identifiant", auto: 'societe->getSocietesLieesIds()' }
        maison_mere_identifiant: { nom: "maison_mere_identifiant", auto: 'societe->getSocieteMaisonMereIdentifiant()' }
        maison_mere_raison_sociale: { nom: "maison_mere_raison_sociale", auto: 'societe->getSocieteMaisonMereRaisonSociale()' }
        maison_mere_siret: { nom: "maison_mere_siret", auto: 'societe->getSocieteMaisonMereSiret()' }
        date_creation: { nom: "date_creation" }
        date_cloture: { nom: "date_cloture" }
        db2_num_tiers: { nom: "db2_num_tiers" }
        db2_num_stock: { nom: "db2_num_stock" }
