<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of class VracStatutAndTypeView
 * @author mathurin
 */
class VracSoussigneIdentifiantView extends acCouchdbView {

  const VRAC_VIEW_KEY_ETABLISSEMENT = 0;
  const VRAC_VIEW_KEY_CAMPAGNE = 1;
  const VRAC_VIEW_KEY_DATE_SIGNATURE = 2;
  const VRAC_VIEW_KEY_STATUT = 3;
  const VRAC_VIEW_KEY_TELEDECLARE = 4;

const VRAC_VIEW_VALUE_CAMPAGNE = 0;
const VRAC_VIEW_VALUE_STATUT = 1;
const VRAC_VIEW_VALUE_ID = 2;
const VRAC_VIEW_VALUE_NUMERO_CONTRAT = 3;
const VRAC_VIEW_VALUE_NUMERO_ARCHIVE = 4;
const VRAC_VIEW_VALUE_ACHETEUR_IDENTIFIANT = 5;
const VRAC_VIEW_VALUE_ACHETEUR_NOM = 6;
const VRAC_VIEW_VALUE_VENDEUR_IDENTIFIANT = 7;
const VRAC_VIEW_VALUE_VENDEUR_NOM = 8;
const VRAC_VIEW_VALUE_MANDATAIRE_IDENTIFIANT = 9;
const VRAC_VIEW_VALUE_MANDATAIRE_NOM = 10;
const VRAC_VIEW_VALUE_REPRESENTANT_IDENTIFIANT = 11;
const VRAC_VIEW_VALUE_REPRESENTANT_NOM = 12;
const VRAC_VIEW_VALUE_TYPE_TRANSACTION = 13;
const VRAC_VIEW_VALUE_PRODUIT_HASH = 14;
const VRAC_VIEW_VALUE_PRODUIT_LIBELLE = 15;
const VRAC_VIEW_VALUE_VOLUME_PROPOSE = 16;
const VRAC_VIEW_VALUE_VOLUME_ENLEVE = 17;
const VRAC_VIEW_VALUE_PRIX_INITIAL_UNITAIRE = 18;
const VRAC_VIEW_VALUE_PRIX_UNITAIRE = 19;
const VRAC_VIEW_VALUE_PRIX_VARIABLE = 20;
const VRAC_VIEW_VALUE_CONTRAT_INTERNE = 21;
const VRAC_VIEW_VALUE_ORIGINAL = 22;
const VRAC_VIEW_VALUE_TYPE_CONTRAT = 23;
const VRAC_VIEW_VALUE_DATE_SIGNATURE = 24;
const VRAC_VIEW_VALUE_DATE_CAMPAGNE = 25;
const VRAC_VIEW_VALUE_DATE_SAISIE = 26;
const VRAC_VIEW_VALUE_MILLESIME = 27;
const VRAC_VIEW_VALUE_CATEGORIE_VIN = 28;
const VRAC_VIEW_VALUE_DOMAINE = 29;
const VRAC_VIEW_VALUE_PART_VARIABLE = 30;
const VRAC_VIEW_VALUE_REPARTITION = 31;
const VRAC_VIEW_VALUE_CVO_NATURE = 32;
const VRAC_VIEW_VALUE_CEPAGE = 33;
const VRAC_VIEW_VALUE_CEPAGE_LIBELLE = 34;
const VRAC_VIEW_VALUE_CREATEUR_IDENTIFIANT = 35;


    public static function getInstance() {
        return acCouchdbManager::getView('vrac', 'soussigneidentifiant', 'Vrac');
    }

}
