all: web/css/compile.css

web/css/compile.css: web/css/compile.less web/css/alerte.less web/css/contact.less  web/css/ds.less web/css/mobile.less web/css/sv12.less web/css/vars.less web/css/annuaire.less web/css/contrat.less web/css/facture.less web/css/principal.less web/css/tablette.less web/css/compile.less web/css/drm.less web/css/global.less web/css/revendication.less web/css/toolbox.less web/css/tooltip.less
	lessc web/css/compile.less > web/css/compile.css
