all:
  configuration:
    facture:
      pdf_nom_interpro: "InterLoire"
      pdf_ordre_cheque: "InterLoire"
      prefix_sage: "VEN"
      tva_compte: "XXXXXXXX"
      type_cvo:
        identifiant_prefix: "1"
      type_libre:
        identifiant_prefix: "1"
      idcontrat: "ARCHIVE"
      stockage_code_produit: "identifiant_analytique"
      pdf_produit: false
      pdf_nom_ref_client: "REF CLIENT"
      pdf_nom_taux: "Taux"
      pdf_display_code_comptable: true
      echeance: "+30 days"
      exercice: "viticole"
