---
- name: "elastisearch key"
  become: true
  apt_key: id=D27D666CD88E42B4 url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present

- name: "elasticsearch repo"
  become: true
  apt_repository: repo="{{item}}" state=present
  with_items:
  - "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main"
  - "deb http://packages.elastic.co/logstash/2.2/debian stable main"
  - "deb http://packages.elastic.co/kibana/4.1/debian stable main"

- name: "backport repo"
  become: true
  apt_repository: repo='deb http://ftp.debian.org/debian stable-backports main' state=present

- name: "modules debian installés"
  apt: name={{item}} state=latest
  become: yes
  with_items:
  - apache2
  - libapache2-mod-php5
  - php5-curl
  - php5-json
  - php5-ldap
  - php5-readline
  - xinetd
  - tinc
  - git-core
  - node-less
  - texlive-fonts-recommended
  - texlive-latex-extra
  - texlive-latex-base
  - pdftk
  - texlive-lang-french
  - texlive-lang-greek
  - latexmk
  - sudo
  - vim
  - rkhunter
  - fail2ban
  - curl
  - dehydrated
  - dehydrated-apache2
  - gawk
  - libjson-perl
  - screen
  - recode
  - unzip

- name: "user actualys exist"
  user: name=actualys state=present
  become: yes

- name: "bonne version git"
  become_user: actualys
  git: repo=https://github.com/24eme/giilda.git
    dest=/home/actualys/{{giilda_branch}}_{{giilda_instance}}
    update=yes clone=yes version={{giilda_branch}} remote={{giilda_branch}}
    force=yes

- name: "cache and log created"
  become: yes
  file: path=/home/actualys/{{giilda_branch}}_{{giilda_instance}}/project/{{item}}
    state=directory mode=2775 owner=www-data group=actualys
  with_items:
  - cache
  - log
  - web/generation
  - data/latex

- name: "Prepare Virtual document root"
  become: yes
  file: path=/home/www state=directory owner=actualys

- name: "Apache modules"
  become: yes
  apache2_module: state=present name={{item}}
  with_items:
  - rewrite
  - vhost_alias
  - ssl
  notify: reload apache

- name: "configuration dehydrated/letsencrypt"
  become: true
  template: src={{item.src}} dest={{item.dest}} mode={{item.mode}}
  with_items:
  - {src: dehydrated/domain.txt.j2, dest: /etc/dehydrated/domains.txt, mode: "0644"}
  - {src: dehydrated/config.sh.j2, dest: /etc/dehydrated/conf.d/config.sh, mode: "0755"}
  - {src: dehydrated/hook.sh.j2, dest: /etc/dehydrated/hook.sh, mode: "0755"}
  - {src: dehydrated/crontab.weekly.j2, dest: /etc/cron.weekly/dehydrated, mode: "0755"}

- name: "Create virtualhost"
  become: yes
  file: path=/home/www/{{giilda_hostname}} state=link src=/home/actualys/{{giilda_branch}}_{{giilda_instance}}/project/web
  notify: reload apache

- name: "Configuration default apache"
  become: yes
  copy: src=files/apache.conf dest=/etc/apache2/sites-enabled/000-default.conf
  notify: reload apache

- name: "Configuration apache pour notre site"
  become: yes
  template: src=templates/apache.conf.j2 dest=/etc/apache2/sites-enabled/{{giilda_hostname}}.conf
  notify: reload apache

- name: "Has couchdb package"
  become: yes
  get_url: url=http://ftp.debian.org/debian/pool/main/c/couchdb/couchdb_1.4.0-3+b1_amd64.deb dest=/var/cache/apt/archives/
  register: couchdb

- name: "Couchdb started"
  become: yes
  apt: deb=/var/cache/apt/archives/couchdb_1.4.0-3+b1_amd64.deb state=present
  when: couchdb|changed

- name: "Elasticsearch present et started"
  become: yes
  apt: name={{item}} state=present
  with_items:
  - openjdk-7-jre
  - elasticsearch

- name: "Plugin head present"
  become: yes
  shell: /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head
  args:
    creates: /usr/share/elasticsearch/plugins/head

- name: "Logstash and kibana"
  apt: name={{item}} state=present
  become: yes
  with_items:
  - logstash
  - kibana

- name: "ELK started"
  service: name={{item}} state=started
  become: yes
  with_items:
  - elasticsearch
  - logstash
  - kibana

- name: "GIILDA Configuration"
  template: src={{item.src}} dest=/home/actualys/{{giilda_branch}}_{{giilda_instance}}/project/{{item.dest}}
  with_items:
  - {src: symfony/declaration_dev.php.j2, dest: web/declaration_dev.php}
  - {src: symfony/databases.yml.j2, dest: config/databases.yml}
  - {src: symfony/app.yml.j2, dest: config/app.yml}
  - {src: config.inc.j2, dest: bin/config.inc}


- name: "GIILDA xinetd"
  become: true
  template: src=xinetd.d/{{item}}.j2 dest=/etc/xinetd.d/{{item}}
  with_items:
  - elasticsearch
  - couchdb
  notify: reload xinetd

- name: "Make viewes"
  shell: make
  args:
    chdir: /home/actualys/{{giilda_branch}}_{{giilda_instance}}/project


#- name: "logstash configuration"
#  shell: bash bin/elastic2_configure
#  args:
#    chdir: /home/actualys/{{giilda_branch}}_{{giilda_instance}}/project
#    creates: /etc/logstash/conf.d/{{giilda_dbname}}.conf
