# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    # content-type: text/html
    X-UA-Compatible: IE=edge,chrome=1

  metas:
    title:        Vins de Loire
    description:  Vins de Loire
    keywords:     Vins de Loire
    language:     fr
    robots:       index, follow
    author:       Actualys
    viewport:       width=device-width, initial-scale=1.0
    copyright:       Vins de Loire - 2012

  stylesheets:    [compile.css]

  javascripts:    [lib/modernizr-2.js]

  has_layout:     true
  layout:         layout