# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: global, action: home}

accueil:
  url:   /accueil
  param: { module: global, action: accueil}

accueil_etablissement:
  url:   /accueil/:identifiant
  param: { module: global, action: accueilEtablissement}
# TELEDECLARATION

auth_login_no_cas:
  url:   /login_no_cas
  param: { module: auth, action: login}


auth_logout:
  url:   /logout
  param: { module: auth, action: logout}

auth_deconnexion_usurpation:
  url:   /deconnexion_usurpation
  param: { module: auth, action: deconnexionUsurpation}
