ivso:
  configuration:
    drm:
      negoce: false
      details:
        export_detail:
          required: []
        vrac_detail:
          creation: false

ivbd:
  configuration:
    drm:
      negoce: false
      details:
        export_detail:
          required: ["identifiant"]
        vrac_detail:
          creation: false


sancerre:
  configuration:
    drm:
      negoce: true
      details:
        export_detail:
          required: ["identifiant"]
        vrac_detail:
          creation: true
