ivso:
  configuration:
    drm:
      negoce: false
      details:
        export_detail:
          required: []
        vrac_detail:
          creation: false
      export_pays_debut: { "UE": "Union Européenne", "HORSUE": "Hors Union Européenne" }
      export_pays_fin: { "inconnu": "Inconnu" }

ivbd:
  configuration:
    drm:
      negoce: false
      details:
        export_detail:
          required: ["identifiant"]
        vrac_detail:
          creation: false
      export_pays_debut: { }
      export_pays_fin: { "inconnu": "Inconnu" }


sancerre:
  configuration:
    drm:
      negoce: true
      details:
        export_detail:
          required: ["identifiant"]
        vrac_detail:
          creation: true
      export_pays_debut: { }
      export_pays_fin: { "AUTRE": "Autres pays"}
