ivso:
  configuration:
    facture:
      prefix_sage: "02"
      tva_compte: "44571502"
      type_cvo:
        identifiant_prefix: "C"
      type_libre:
        identifiant_prefix: "L"
      idcontrat: "ID"
      stockage_code_produit: "code_compte"
      pdf_produit: false

ivbd:
  configuration:
    facture:
      prefix_sage: "VEN"
      tva_compte: "44570100"
      type_cvo:
        identifiant_prefix: "1"
      type_libre:
        identifiant_prefix: "1"
      idcontrat: "ARCHIVE"
      stockage_code_produit: "identifiant_analytique"
      pdf_produit: false

sancerre:
  configuration:
    facture:
      prefix_sage: ""
      tva_compte: ""
      type_cvo:
        identifiant_prefix: ""
      type_libre:
        identifiant_prefix: ""
      idcontrat: "ARCHIVE"
      stockage_code_produit: "identifiant_analytique"
      prefix_code_comptable: "4110"
      pdf_produit: true
