ivso:
  configuration:
    facture:
      pdf: "facture/pdf_generique"
      pdf_nom_interpro: "IVSO"
      pdf_ordre_cheque: "Interprofession des Vins du Sud Ouest"
      prefix_sage: "02"
      tva_compte: "44571502"
      type_cvo:
        identifiant_prefix: "C"
      type_libre:
        identifiant_prefix: "L"
      idcontrat: "ID"
      stockage_code_produit: "code_compte"
      pdf_produit: false
      pdf_nom_ref_client: "N째 IVSO"
      pdf_nom_taux: "Taux"
      pdf_display_code_comptable: true
      echeance: "+30 days"

ivbd:
  configuration:
    facture:
      pdf: "facture/pdf_generique"
      pdf_nom_interpro: "IVBD"
      pdf_ordre_cheque: "Interprofession IVBD"
      prefix_sage: "VEN"
      tva_compte: "44570100"
      type_cvo:
        identifiant_prefix: "1"
      type_libre:
        identifiant_prefix: "1"
      idcontrat: "ARCHIVE"
      stockage_code_produit: "identifiant_analytique"
      pdf_produit: false
      pdf_nom_ref_client: "N째 IVBD"
      pdf_nom_taux: "Taux"
      pdf_display_code_comptable: true
      echeance: "+30 days"

sancerre:
  configuration:
    facture:
      pdf: "facture/pdf_generique"
      pdf_nom_interpro: "Bureau Interprofessionnel des Vins du Centre"
      pdf_ordre_cheque: "Bureau Interprofessionnel des Vins du Centre"
      prefix_sage: ""
      tva_compte: ""
      type_cvo:
        identifiant_prefix: ""
      type_libre:
        identifiant_prefix: ""
      idcontrat: "ARCHIVE"
      stockage_code_produit: "identifiant_analytique"
      prefix_code_comptable: "4110"
      pdf_produit: true
      pdf_nom_ref_client: "N째 BIVC"
      pdf_nom_taux: "Cotisat째"
      pdf_display_code_comptable: false
      echeance: "last day of +1 month"
