all:
  configuration:
    points_aides:
      vrac:
        menu_list_asigner : "Contrats d’achats en attente de votre signature. Ces contrats, initiés par un négociant ou un courtier, doivent être lus avant validation définitive."
        menu_list_enattente: "Contrats d’achats dont vous êtes l’initiateur  et qui restent en attente des signatures de tous les contractants."
        menu_acceder: "Permet d’accéder à l’ensemble de vos contrats."
      drm:
        menu_list : "Permet d’accéder à la dernière DRM pour la créer, la finir ou la visualiser ."
        menu_acceder: "Permet d’accéder à l’ensemble de vos DRM."
        changement_campagne : "Sélectionner une campagne particulière ou les 6 derniers mois puis cliquer sur le bouton changer."
        etats : "Indique l’état de la DRM: à créer, à finir, validée ou saisie interne. L’état « saisie interne » indique une DRM papier saisie par l’interprofession: ces DRM ne peuvent être consultées ici. "
        creation_nouvelle : "Crée une nouvelle DRM."
        creation_vierge : "Crée une DRM sans mouvement. A utiliser uniquement si aucun mouvement d’entrée et de sortie n’a eu lieu dans le mois."
        creation_edi : "Permet d’importer directement votre DRM à partir de votre logiciel de gestion. Contacter l’interprofession pour  connaître les logiciels compatibles."
        produits : "Indiquer les produits que vous détenez. Vous pourrez à tout moment en rajouter."
        produits_coche_suspendu : "C’est le régime général. Les capsules CRD que vous utilisez peuvent être personnalisées (donc forcément achetées en droits suspendus) ou banalisées (achetées en droits suspendus ou acquittés). Le montant des droits d’accise pour les capsules achetées en droits suspendus est comptabilisé à la sortie du chai, c’est-à-dire en fin de DRM.  Le paiement de ces droits d’accise aux douanes peut alors se faire annuellement pour les opérateurs dispensés de caution, ou bien chaque mois pour tous les autres."
        produits_coche_acquitte : "Ce régime est exceptionnel. Pour les vins que vous produisez, les capsules CRD utilisées sont forcément des capsules banalisées achetées en droits acquittés.<br/>Pour les vins que vous détenez mais dont vous n’êtes pas producteur, peu importe la capsule CRD utilisée: les droits ont été acquittés par le producteur."
        mouvements_autres_entrees : "Cliquer pour développer ou réduire les autres entrées. Pour rendre l'une de ces entrées visible par défaut, clicker sur l'étoile blanche à gauche de l'intitulé."
        mouvements_autres_sorties: "Cliquer pour développer ou réduire les autres sorties. Pour rendre l'une de ces sorties visible par défaut, clicker sur l'étoile blanche à gauche de l'intitulé."
        mouvements_choix_produits: "Liste de tous les produits que vous détenez. Pour ajouter un produit, commencer à le saisir dans la barre «ajouter un produit» : les produits possibles seront sélectionnés au fur et à mesure en fonction des caractères saisis. Ci dessous une liste de l'ensemble de vos produits est disponible. Un code couleur indique l’état du produit: saisi, en cours, à saisir. L’icône « oeuil » permet  de masquer ou afficher la colonne du produit."
        mouvements_contrats_numero : "Sélectionner le contrat correspondant au volume à sortir en saisissant l’un des éléments listés:  nom de l’acheteur - n° de bordereau (n° de contrat/visa de l’interprofession) - volume du contrat. Les volumes indiqués sont: volume restant à retirer hl [volume déjà retiré/volume initial du contrat]."
        mouvements_contrats_doc_accompagnement : "Vous pouvez indiquer le type de document d’accompagnement utilisé et ses références."
        mouvements_contrats_supprimer: "Supprimer la ligne."
        mouvements_contrats_ajouter: "Ajouter une ligne pour indiquer une autre retiraison."
        mouvements_contrats_type_doc: "Indiquer le type de document utilisé: DAA/DAC/DCA; DSA/DSAC; DAE; Empreinte."
        mouvements_contrats_doc_accompagnement_num: "Indiquer le numéro du document utilisé."
        mouvements_export_pays: "Indiquer le pays d’exportation en saisissant le nom du pays ou en le sélectionnant dans la liste."
        mouvements_export_doc_accompagnement: "Vous pouvez préciser ici le type de document d’accompagnement utilisé et ses références."
        mouvements_export_type_doc: "Indiquer le type de document utilisé: DAA/DAC/DCA; DSA/DSAC; DAE; Empreinte."
        mouvements_export_doc_accompagnement_num: "Indiquer le numéro du document utilisé."
        crd_type : "Indiquer les mouvements de CRD par type (vertes = AOC; bleues = IGP/VSIG; lies de vin = tous vins) et centilisation."
        crd_stock_debut : "Indiquer le stock de départ (au 1er août pour une campagne complète). Le stock est ensuite calculé automatiquement."
        crd_entree_achat : "Indiquer les achats de capsules CRD ."
        crd_entree_retour : "Indiquer les retours éventuels de capsules en cas de retour de vin."
        crd_entree_exc : "Indiquer les capsules constatées en excédent lors d’un inventaire ou d’un contrôle douanier."
        crd_sortie_utilisee : "Indiquer les capsules utilisées (= capsules sorties physiquement du chai pour commercialisation, y compris éventuellement à l’export)."
        crd_sortie_detruite : "Indiquer  les capsules détruites."
        crd_sortie_manquant : "Indiquer les capsules constatées manquantes lors d’un inventaire ou d’un contrôle douanier."
        crd_stock_fin : "Le stock de fin de mois est calculé automatiquement."
        annexe_document_accompagnement: "Indiquer les documents utilisés dans le mois."
        annexe_daadac : "DAA/DAC (=DCA)"
        annexe_dsadsac : "DSA/DSAC. Documents servant pour la vente à un débitant, un particulier ou un entrepositaire agréé ne travaillant qu’en droits acquittés (n° d’identification sous la forme FR 000 000 A 0000)."
        annexe_empreinte : "Empreinte. Uniquement en cas de détention d’une machine à timbrer."
        annexe_nonapurement: "Indiquer les documents d’accompagnement en droits suspendus non apurés 3 mois après la date d’expédition."
        annexe_nonapurement_num_doc: "Indiquer le n° de document."
        annexe_nonapurement_date: "Indiquer la date d’expédition du vin."
        annexe_nonapurement_num_accise: "Indiquer le n° d’accise du destinataire."
        annexe_observations: "La douane exige que vous remplissiez les observations concernant les mouvements retour de vin, transfert de comptabilité matières,  destruction, excédents ou manquants pour les vins suivants."
        annexe_statistique_eur: "Veuillez indiquer ci dessous vos quantités de moûts transformées en jus de raisin, MCR et vinaigre."
        annexe_paiement_douane: "Choisissez ici les conditions de paiement aux douanes. En fréquence annuelle un cumul du paiement aux douanes est calculé et vous avez la possibilité ici de le maintenir à jour."
        recapitulatif_stock: "Résumé: récapitulation synthétique par produit des stocks initiaux et finaux ainsi que des totaux des entrées et des sorties."
        recapitulatif_details: "Détails: liste chaque mouvement de chaque produit."
        recapitulatif_pt_bloquant:  "Les points bloquants doivent être résolus avant de valider la DRM. Pour cela, cliquer sur l’hyperlien."
        recapitulatif_pt_vigilance:  "Points non bloquants. Vous pouvez résoudre le point en cliquant sur l’hyperlien."

        visualisation_cvo: "Les indications portées dans ce tableau sont une simple estimation indicative et non contractuelle.  Se reporter à la facture de l’interprofession pour le détail des CVO et au portail CIEL pour les droits de circulation."
        visualisation_cvo_volume_fact: "Le volume indiqué est la somme des volumes sujets à CVO, tous vins confondus, à payer par le déclarant."
        visualisation_cvo_montant: "Le montant indiqué correspond au total des CVO dues pour le mois par le déclarant."
        visualisation_droit_volume: "Le volume indiqué est la somme des volumes, tous vins confondus, détenus par le déclarant en droits suspendus et mis à la consommation en France dans le mois."
        visualisation_droit_taux: "Les taux sont indicatifs. Ils changent chaque année au 1er janvier."
        visualisation_droit_montant: "Le montant indiqué correspond au total des droits d’accise dus pour le mois par le déclarant."
        visualisation_pdf: "Permet de télécharger un fichier PDF pour pouvoir imprimer la DRM. Utile par exemple en procédure de secours  dans le cas d’inaccessibilité du site CIEL."
        visualisation_detail_mvt: "Indiquer un produit pour voir uniquement les mouvements liés à ce produit;  un type de mouvement pour voir tous les produits concernés; ou plusieurs éléments de recherche combinés."

        etape_produit_description: "Lister les produits détenus et leurs statuts fiscaux. Afin de mieux préparer votre DRM, vous pouvez préciser ici vos stocks épuisés ou l'absence de mouvements pour tout ou partie des produits."
        etape_mvt_supendus_description: "Indiquer les mouvements d’entrée et de sortie du stock en droits suspendus."
        etape_mvt_acquittes_description: "Indiquer les mouvements d’entrée et de sortie du stock en droits acquittés."
        etape_capsules_crd_description: "Indiquer les mouvements d’entrée et de sortie du stock de capsules CRD."
        etape_annexes_description: "Indiquer les documents d’accompagnement utilisés, le sucre utilisé et toute observation obligatoire ou facultative."
        etape_recap_description: "Récapitulatif de la DRM saisie et validation."
ivso:
  configuration:
    points_aides:
      drm:
        mouvements_export_pays: "Indiquer le pays d’exportation en saisissant le nom du pays ou en le sélectionnant dans la liste. A minima, indiquer « Union Européenne » ou « Hors Union Européenne »."


ivbd:
  configuration:
    points_aides:
      drm:
        mouvements_export_pays: "Indiquer le pays d’exportation en saisissant le nom du pays ou en le sélectionnant dans la liste."
