ivso:
  configuration:
    sv12:
      raisinetmout: false
      actif: false
ivbd:
  configuration:
    sv12:
      raisinetmout: false
      actif: false

sancerre:
  configuration:
    sv12:
      raisinetmout: false
