ivso:
  configuration:
    vrac:
      pdf: "vrac/pdf_ivso"
      solde_seuil: "10%"
      repartition_cvo: "50"
      region_departement: ".*"
      champs_supprimes:
        condition:
          "_ALL": ["tva", "pluriannuel", "annee_contrat", "seuil_revision", "pourcentage_variation", "courtage_taux", "courtage_repartition"]
          "RAISINS": ["autorisation_nom_vin", "autorisation_nom_producteur", "preparation_vin", "embouteillage", "conditionnement_crd"]
          "MOUTS": ["autorisation_nom_vin", "autorisation_nom_producteur", "preparation_vin", "embouteillage", "conditionnement_crd"]
          "VIN_VRAC": ["preparation_vin", "embouteillage", "conditionnement_crd"]
          "VIN_BOUTEILLE": []
      delais_paiement:
        "60_JOURS": "60 jours fin de mois"
        "30_JOURS": "30 jours fin de mois"
        "COMPTANT": "Comptant"
        "ACCORD_INTERPROFESSIONNEL": "Accord Interprofessionnel (Maximum de 75 jours à partir de la date de retiraison effective)"
        "45_JOURS": "45 jours à compter du mois d'émission de la facture"
      moyens_paiement:
        "VIREMENT": "Virement bancaire"
        "CB": "Carte bancaire"
        "CHEQUE": "Chèque"
        "ESPECES": "Espèces"
      transactions:
        "MOUTS": null

ivbd:
  configuration:
    vrac:
      pdf: "vrac/pdf_ivbd"
      solde_seuil: "9"
      repartition_cvo: "100_ACHETEUR"
      region_departement: "^(24|33|46|47)"
      champs_supprimes:
        condition:
          "_ALL": ["date_debut_retiraison", "pluriannuel", "annee_contrat", "seuil_revision", "pourcentage_variation", "acompte"]
          "RAISINS": ["autorisation_nom_vin", "autorisation_nom_producteur", "preparation_vin", "embouteillage", "conditionnement_crd"]
          "MOUTS": ["autorisation_nom_vin", "autorisation_nom_producteur", "preparation_vin", "embouteillage", "conditionnement_crd"]
          "VIN_VRAC": ["preparation_vin", "embouteillage", "conditionnement_crd", "cahier_charge"]
          "VIN_BOUTEILLE": ["cahier_charge"]
      unites:
        "MOUTS":
          "prix_initial_unitaire":
            "cle": "EURO_TONNEAU"
            "libelle": "€/T"
        "VIN_VRAC":
          "prix_initial_unitaire":
            "cle": "EURO_TONNEAU"
            "libelle": "€/T"
        "VIN_BOUTEILLE":
          "prix_initial_unitaire":
            "cle": "EURO_TONNEAU"
            "libelle": "€/T"
      moyens_paiement:
        "TRAITE": "Traite"
        "CHEQUE": "Chèque"
        "VIREMENT": "Virement"
        "CB": "Carte bancaire"
        "VALEURS": "Valeurs"
        "ESPECES": "Espèces"
        "BILLET_ORDRE": "Billet à ordre"
        "AUTRE": "Autre / non précisé"
      delais_paiement:
        "60_JOURS": "60 jours"
        "75_JOURS": "75 jours"
        "45_JOURS": "45 jours"
        "30_JOURS": "30 jours"
        "10_JOURS": "10 jours"
        "PLUS_75_JOURS": "Au-delà de 75 jours"
        "COMPTANT": "A réception de facture / comptant"
        "AUTRE": "Autre / non précisé"
      transactions:
        "VIN_VRAC": "<span class=\"icon-vrac\" style=\"font-size: 32px;\"></span> Vrac retiraison vrac"
        "MOUTS": null
