ivso:
  configuration:
    vrac:
      pdf: "vrac/pdf_ivso"
      champs:
        condition: ["acompte", "cahier_charge", "reference_contrat", "delai_paiement", "moyen_paiement", "date_limite_retiraison", "date_debut_retiraison", "conditions_particulieres", "clause_reserve_propriete", "autorisation_nom_vin", "autorisation_nom_producteur", "preparation_vin", "embouteillage", "conditionnement_crd"]
      delais_paiement:
        "60_JOURS": "60 jours fin de mois"
        "30_JOURS": "30 jours fin de mois"
        "90_JOURS": "90 jours fin de mois"
        "COMPTANT": "Comptant"
        "ACCORD_INTERPROFESSIONNEL": "Accord Interprofessionnel (Maximum de 75 jours à partir de la date de retiraison effective)"
        "45_JOURS": "45 jours à compter du mois d'émission de la facture"
ivbd:
  configuration:
    vrac:
      pdf: "vrac/pdf_ivbd"
      champs:
        condition: ["acompte", "cahier_charge", "reference_contrat", "delai_paiement", "moyen_paiement", "date_limite_retiraison", "conditions_particulieres", "clause_reserve_propriete", "autorisation_nom_vin", "autorisation_nom_producteur", "preparation_vin", "embouteillage", "conditionnement_crd", "taux_courtage", "taux_repartition"]
      unites:
        "MOUTS":
          "prix_initial_unitaire":
            "cle": "EURO_TONNEAU"
            "libelle": "€/T"
        "VIN_VRAC":
          "prix_initial_unitaire":
            "cle": "EURO_TONNEAU"
            "libelle": "€/T"
        "VIN_BOUTEILLE":
          "prix_initial_unitaire":
            "cle": "EURO_TONNEAU"
            "libelle": "€/T"
      delais_paiement:
        "COMPTANT": "Comptant"
        "30_JOURS": "30 jours fin de mois"
        "45_JOURS": "45 jours fin de mois"
        "60_JOURS": "60 jours fin de mois"
        "75_JOURS": "75 jours fin de mois"