ivso:
  configuration:
    vrac:
      pdf: "vrac/pdf_ivso"
      champs:
        soussigne: ["vendeur_tva", "acheteur_type", "vendeur_identifiant", "acheteur_producteur", "acheteur_negociant", "mandataire_identifiant", "responsable", "type_transaction", "interne", "mandataire_exist", "logement_exist", "logement", "vendeur_intermediaire"]
        condition: ["acompte", "cahier_charge", "reference_contrat", "delai_paiement", "moyen_paiement", "date_limite_retiraison", "date_debut_retiraison", "cvo_repartition", "conditions_particulieres", "clause_reserve_propriete", "autorisation_nom_vin", "autorisation_nom_producteur", "taux_courtage", "preparation_vin", "embouteillage", "conditionnement_crd"]
ivbd:
  configuration:
    vrac:
      pdf: "vrac/pdf_ivbd"

