all:
  configuration:
    societe:
      droits:
        teledeclaration: "Télédéclaration",
        teledeclaration_vrac: "Création contrats"
        teledeclaration_vrac_creation: "Création contrats"
        teledeclaration_drm: "DRM"
        teledeclaration_douane: "Transmission Ciel"
